name: Generate Stats Images

on:
  push:
    branches: [ master ]
  schedule:
    - cron: "5 0 * * *"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Check out the repository
    - uses: actions/checkout@v3

    # Step 2: Set up Python 3.8
    - name: Set up Python 3.8
      uses: actions/setup-python@v4
      with:
        python-version: '3.8'
        architecture: 'x64'
        cache: 'pip'

    # Step 3: Install dependencies
    - name: Install requirements
      run: |
        python3 -m pip install --upgrade pip setuptools wheel
        python3 -m pip install -r requirements.txt

    # Step 4: Generate the images
    - name: Generate images
      run: |
        python3 --version
        python3 generate_images.py
      env:
        ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        EXCLUDED: ${{ secrets.EXCLUDED }}
        EXCLUDED_LANGS: ${{ secrets.EXCLUDED_LANGS }}
        EXCLUDE_FORKED_REPOS: "true"

    # --- START: THE DEFINITIVE FIX ---
    # Step 5: Verify that BOTH images were created successfully.
    - name: Verify generated files
      run: |
        echo "Checking contents of the 'generated' directory..."
        ls -l generated/
        if [ ! -f generated/overview.svg ] || [ ! -f generated/languages.svg ]; then
          echo "Error: One or more required SVG files were not generated!"
          echo "This usually happens due to a GitHub API rate limit or an error during language analysis."
          exit 1
        fi
        echo "✅ Both overview.svg and languages.svg were generated successfully."
    # --- END: THE DEFINITIVE FIX ---

    # Step 6: Commit and push the changes
    - name: Commit and push changes
      run: |
        git config --global user.name "github-stats[bot]"
        git config --global user.email "github-stats[bot]@users.noreply.github.com"
        git add .
        # Only commit and push if there are actual changes
        if git diff --staged --quiet; then
          echo "No changes to commit."
        else
          git commit -m "Update generated stats images"
          # Pull with rebase to handle potential race conditions, then push
          git pull --rebase
          git push
        fi
